### ISSUE TITLE
Legends missing in IPython Notebooks when plotting inline

### ISSUE THREAD

**Issue by ethanwhite** [yhat/ggpy#33]
Thanks for the awesome module!

I've been playing around with it a bit and ran into an issue with legends in IPython Notebooks. Everything works as expected when generating figures external to the notebook (i.e., using `ipython notebook` to launch the notebook), but when plotting inline (``ipython notebook --pylab inline) the legends do not appear.

![screenshot from 2013-10-15 21 44 58](https://f.cloud.github.com/assets/744427/1339434/041fba8e-3605-11e3-9730-f161ca8e0cfe.png)

I expected the legend to appear to the right hand side just as it did when plotting in a separate window.

**Comment by overnin** [comment]
@jml i have same issus on osx 10.9 with matplotlib (1.4.2) and ggplot (0.6.5), the legend doesn't appear. Is there any specific environment variable to setup?

Here is my plot:
```python
plot = ggplot(df_hdiff, aes(x='Hour', y='value', color='variable')) \
    + geom_point() + geom_line() + xlab("Hour of the day") + ylab("Average Number of Riders")\
    + ggtitle("Entries and Exits vs Hour") + scale_color_manual(values=['blue', 'red'])
```

**Comment by overnin** [comment]
Issue fixed with last version of ggplot from github.

**Comment by trebsirk** [comment]
legend still not showing on osx using 
ggplot==0.6.5
ipython==2.3.1
matplotlib==1.4.2
pandas==0.15.2
i'm using %matplotlib inline. 
this is so annoying. I basically can't use ggplot for anything.

**Comment by overnin** [comment]
@trebsirk is the problem persistent when you install the latest commit of ggplot ```pip install git+git://github.com/yhat/ggplot.git```?

**Comment by ntldrake** [comment]
I'm having the same issue with ggplot==0.6.6

**Comment by trebsirk** [comment]
@overnin i used pip install ggplot --upgrade for the latest version, and it chopped off the legend. i have also tried with 0.5.9 with the same results. Is there a different version of matplotlib that could fix this?

**Comment by overnin** [comment]
@trebsirk i don't exactly remember how to fix the issue. Install matpotlib from git may help.

**Comment by ntldrake** [comment]
It only seems to be happening with faceting. 

```python
# Doesn't work
p = ggplot(aes(x='month_id', y='mins_per_video', color='platform_value'), data=df_espn_final2) + \
    geom_line() + \
    ggtitle("%s Minutes Per Video by Platform & Operating System" % web_name) + \
    xlab("Month ID") + \
    ylab("Minutes Per Video") + \
    facet_wrap('device_value', scales='fixed') + \
    xlim(178,181)

p
```

```
# Works
p2 = ggplot(aes(x='month_id', y='mins_per_viewer', color='platform_value'), data=df_espn_final2[(df_espn_final2.device_value=="Smartphone")]) + \
    geom_line() + \
    ggtitle("%s Minutes Per Viewer by Platform & Operating System" % web_name) + \
    xlab("Month ID") + \
    ylab("Minutes Per Viewer") + \
    xlim(178,181)


p2
```

**Comment by PaulMest** [comment]
This code straight from the ggplot examples does not show legends with ggplot 0.6.5:

``` python
    from ggplot import meat
    meat_lng = pd.melt(meat, id_vars=['date'])
        
    gplt = gg.ggplot(gg.aes(x='date', y='value', colour='variable'), data=meat_lng) + \
            gg.geom_line() + \
            gg.theme({'theme_position':'right'})
    
    gg.ggsave(plot=gplt, filename="gplt.png", width=12, height=3, dpi=100)
```
Environment: ggplot 0.6.5 installed via:

`$ pip install ggplot`

I was able to fix by pip installing straight from master:

```bash
$ pip uninstall ggplot
$ pip install git+git://github.com/yhat/ggplot.git
```

The legend now shows up.

My environment:
* Mac OS X Yosemite.
* Python 2.7.8
* Matplotlib 1.4.3
* ggplot 0.6.6

**Comment by relativistic** [comment]
I had same problem as @PaulMest. Same version numbers, except for using OSX Mavericks. I also had installed it using ggplot.

His suggestion of installing directly from the git master fixed it for me as well. Apparently there is a problem with the version pip pulls by default?

**Comment by rcompton** [comment]
Same as @relativistic , clone direct from github and it works

**Comment by edoardovivo** [comment]
I am experiencing the same issue. 

My environment:

* CentOS release 6.6 
* matplotlib: 1.5.1
* ggplot: 0.6.8
* jupyter-core: 4.1.0

My code:

```
p = ggplot(df_PN_melt, aes(x="M", y="value", colour="variable")) + \
    geom_point(size=40) + \
    geom_line(size=3) + \
    facet_wrap("Option", ncol=2) + \
    scale_color_manual(breaks=my_breaks )
print p
```

This does NOT produce a legend neither with ggsave nor with inline visualization in Jupyter.

I see the last comment here is one year old, so I suppose cloning directly from github was a workaround that should be outdated by now.

Any idea?

Thank you
